# Lib

In [1]:
import os
import uuid
import numpy as np
import pandas as pd
import datetime as dt

import matplotlib.pyplot as plt
%matplotlib inline

<img src="flow_codigo_db.png" width=600 height=600 >

<img src="matching2.png" width=800 height=600 >

# Datasets

## Vacine JÃ¡

In [2]:
fname_vacineja = os.path.join("..", "..", "..", "data", "vacinado_obito", "cadastrados_vacineja_202110111044.csv")
df_vacineja = pd.read_csv(fname_vacineja, delimiter=";", nrows=15)
df_vacineja_size = pd.read_csv(fname_vacineja, delimiter=";", nrows=None, usecols=["cpf"])

In [3]:
print(df_vacineja_size.shape[0])
df_vacineja[:5]

1882607

,nome,cpf,data_nascimento,bairro,cidade,sexo,created_at,nome_mae
0,EDILENE GOMES DA SILVA,4119600327,1974-10-20,PASSARE,FORTALEZA,F,2021-05-26 00:00:00,LUCINEIDE GOMES DA SILVA
1,JACKSON BRUNO DOS SANTOS MIRANDA,4285392380,1989-09-07,JANGURUSSU,FORTALEZA,M,2021-04-04 00:00:00,MARIA EUGENIA DOS SANTOS
2,ANTONIA IEDA DE SALES LADISLAU DE LIMA,64130223372,1976-12-08,BARRA DO CEARA,FORTALEZA,F,2021-06-04 00:00:00,TEREZINHA DE SALES LADISLAU
3,MARIA CLEIDE NASCIMENTO DA SILVA,58374531304,1975-12-20,JANGURUSSU,FORTALEZA,F,2021-08-04 00:00:00,MARIA CLEIDE
4,ANTONIA ALYNNE DA SILVA LIMA,3687378373,1994-08-27,BONSUCESSO,FORTALEZA,F,2021-03-26 00:00:00,ADELIA ANA DA SILVA

## Vacinados

In [4]:
fname_vacinados = os.path.join("..", "..", "..", "data", "vacinado_obito", "vacinados_d1d2_update_Sep2_2021.csv")
df_vacinados = pd.read_csv(fname_vacinados, delimiter=",", dtype={"cpf": str}, nrows=15, index_col=0)
df_vacinados_size = pd.read_csv(fname_vacinados, delimiter=",", usecols=["cpf"])

C:\Users\higor.monteiro\Miniconda3\envs\geopandas_testenv\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
print(df_vacinados_size.shape[0])
df_vacinados[:5]

1831084

,nome,cpf,sexo,data nascimento,data D1,data D2,vacina,fornecedor,idade anos,faixa etaria,bairro,bairro id,tipo atendimento,tipo usuario,grupo prioritario,grupo atendimento
0,PALOMA SILVA BASTOS,07139828377,F,1999-09-17,2021-08-14,NaN,PFIZER,PFIZER,21,20 A 24 ANOS,MONTESE,82.0,ROTINA,-,OUTROS,OUTROS
1,FRANCISCA ELIZABETH FERREIRA CAMILO,60660696320,F,1993-10-05,2021-07-21,NaN,PFIZER,PFIZER,27,25 A 29 ANOS,BOM JARDIM,92.0,ROTINA,-,OUTROS,OUTROS
2,MARIA CLARICE SILVA COSTA,09130985315,F,1940-02-17,2021-03-22,2021-04-03,CORONAVAC,BUTANTAN,81,80 A 84 ANOS,PASSARE,145.0,ROTINA-ROTINA,I-I,IDOSO-IDOSO,80E+ ANOS-80E+ ANOS
3,PRISCILA MENEZES DEOLIVEIRA,06560411370,F,1994-05-10,2021-07-30,2021-08-27,CORONAVAC,BUTANTAN,27,25 A 29 ANOS,FLORESTA,4.0,ROTINA-ROTINA,---,OUTROS-OUTROS,OUTROS-OUTROS
4,MAURICIO VIEIRA DA SILVA,56718500372,M,1973-11-10,2021-05-20,2021-08-04,PFIZER,PFIZER,47,45 A 49 ANOS,ALVARO WEYNE,6.0,ROTINA-ROTINA,---,nan-nan,OUTROS-OUTROS

In [6]:
df_vacinados.isnull().sum()

nome                 0
cpf                  0
sexo                 0
data nascimento      0
data D1              0
data D2              7
vacina               0
fornecedor           0
idade anos           0
faixa etaria         0
bairro               0
bairro id            1
tipo atendimento     0
tipo usuario         0
grupo prioritario    0
grupo atendimento    0
dtype: int64

## Gal

In [7]:
fname_gal = os.path.join("..", "..", "..", "data", "testes_covid19", "testes_gal_JAN_AGO2021.csv")
df_gal = pd.read_csv(fname_gal, delimiter=",", nrows=15, index_col=0)
df_gal_size = pd.read_csv(fname_gal, delimiter=",", usecols=["Status Exame"])

In [8]:
print(df_gal_size.shape[0])
df_gal[:5]

366981

,Index tabela original,RequisiÃ§Ã£o,RequisiÃ§Ã£o Correlativo (S/N),Regional de Cadastro,LaboratÃ³rio de Cadastro,CNES LaboratÃ³rio de Cadastro,Unidade Solicitante,CNES Unidade Solicitante,Municipio do Solicitante,IBGE MunicÃ­pio Solicitante,...,Status Exame,LaboratÃ³rio Externo,CNES LaboratÃ³rio Externo,1Âº Campo Resultado,2Âº Campo Resultado,3Âº Campo Resultado,4Âº Campo Resultado,5Âº Campo Resultado,6Âº Campo Resultado,ObservaÃ§Ãµes do Resultado
0,0,210154000349,N,1,UNIDADE PRONTO ATENDIMENTO JOSE WALTER,7274440,UNIDADE PRONTO ATENDIMENTO JOSE WALTER,7274440,FORTALEZA,230440,...,Resultado Liberado,NaN,NaN,Resultado: DetectÃ¡vel,NaN,CT:,NaN,NaN,NaN,Este resultado se refere a amostra analisada.
1,1,210156000227,N,1,UNIDADE PRONTO ATENDIMENTO AUTRAN NUNES,6999506,UNIDADE PRONTO ATENDIMENTO AUTRAN NUNES,6999506,FORTALEZA,230440,...,Resultado Liberado,NaN,NaN,Resultado: DetectÃ¡vel,NaN,CT:,NaN,NaN,NaN,Este resultado se refere a amostra analisada.
2,2,210155000428,N,1,UNIDADE PRONTO ATENDIMENTO CONJUNTO CEARA,7360851,UNIDADE PRONTO ATENDIMENTO CONJUNTO CEARA,7360851,FORTALEZA,230440,...,Resultado Liberado,NaN,NaN,Resultado: DetectÃ¡vel,NaN,CT:,NaN,NaN,NaN,Este resultado se refere a amostra analisada.
3,3,210190000171,N,1,UNIDADE DE PRONTO ATENDIMENTO VILA VELHA,7980310,UNIDADE DE PRONTO ATENDIMENTO VILA VELHA,7980310,FORTALEZA,230440,...,Resultado Liberado,NaN,NaN,Resultado: DetectÃ¡vel,NaN,CT:,NaN,NaN,NaN,Este resultado se refere a amostra analisada.
4,4,210159000856,N,1,UNIDADE PRONTO ATENDIMENTO JANGURUSSU,7429398,UNIDADE PRONTO ATENDIMENTO JANGURUSSU,7429398,FORTALEZA,230440,...,Resultado Liberado,NaN,NaN,Resultado: DetectÃ¡vel,NaN,CT:,NaN,NaN,NaN,Este resultado se refere a amostra analisada.

## IntegraSUS

In [9]:
fname_integra = os.path.join("..", "..", "..", "data", "testes_covid19", "base_dados_integrasus_fortaleza_final.csv")
df_integra = pd.read_csv(fname_integra, delimiter=",", nrows=15, index_col=0)
df_integra_size = pd.read_csv(fname_integra, delimiter=",", usecols=["id_esus"])

In [10]:
print(df_integra_size.shape[0])
df_integra[:5]

182073

,id,codigo_paciente,codigo_obito,id_redcap,classificacao_estado_redcap,id_esus,classificacao_estado_esus,classificacao_final_esus,evolucao_caso_esus,cbo_esus,...,data_obito_temp,data_nascimento_temp,codigo_obito_temp,dup,classi_fin,tipo_teste_exame,selecao,mes_sintomas,ano_sintomas,fase
0,1105454769,000031a4ed0718fe9c8d3dfef523c850,c2d850bea34a750409aeb1847a99e0c2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,.,10044,ANAALINEMARTINSDOSSANTOSSOUSA10044.,0.0,CONFIRMADO,RT-PCR,1.0,3,2021,2.0
1,1105575430,0001846c71bb644266e8f7c43458af31,2c56d9fb31aace17578b2aeb9d4c79cf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,.,11538,FRANCISCOFABRICIODELIMABARROSO11538.,0.0,CONFIRMADO,RT-PCR,1.0,4,2021,2.0
2,1105488924,0001c767f54644e351b441e9dc62cf66,0fc4604428eca30f87b3f7a74cf669c4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,.,15206,ALEXFERREIRADESALES15206.,0.0,CONFIRMADO,RT-PCR,1.0,4,2021,2.0
3,1105498107,0001f632bda731380d0ee25a685fd44a,149384e9363304f15101078759650794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,.,6379,JOSERONYCARNEIROARAUJO6379.,0.0,CONFIRMADO,RT-PCR,1.0,4,2021,2.0
4,1104222431,0001fbe0da8f4009c8ceb1a427627653,15bd4bbb5c2db08a908fd38b725e3701,NaN,NaN,2.321681e+11,NaN,NaN,NaN,NaN,...,22357,-4383,FRANCISCOALISIONEPOMUCENO-438322357,1.0,CONFIRMADO,RT-PCR,1.0,2,2021,2.0

## Deaths covid (SIM)

In [12]:
fname_covid = os.path.join("..", "..", "..", "data", "obitos_covid19", "base_dados_obitos_cevepi.csv")
df_covid = pd.read_csv(fname_covid, delimiter=";", nrows=None, encoding="latin")

C:\Users\higor.monteiro\Miniconda3\envs\geopandas_testenv\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (52,98,99,113) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [13]:
print(df_covid.shape[0])
df_covid.iloc[:5,4:]

11386

,numerodo,nu_requisicao_lab,id_geo,nome,sexo,data_nascimento,nome_mae,idade_anos,nu_idade_n,fx_etaria,...,data_nascimento_temp,data_obito_temp,codigo_paciente_temp,codigo_obito_temp,ano_obito,mes_obito,ano_sintomas,mes_sintomas,number,fase
0,29582542,NaN,NaN,CARMEZITA SANTOS DO NASCIMENTO,FEM,03/11/1963,NaN,56,4056.0,55 A 59 ANOS,...,1402,22030,CARMEZITASANTOSDONASCIMENTOFEM1402,CARMEZITASANTOSDONASCIMENTO,2020.0,4.0,NaN,NaN,1,NaN
1,31486151,NaN,NaN,ALDEMIR RODRIGUES DE BRITO,MASC,27/05/1964,BERENICE RODRIGUES DE BRITO,57,4057.0,55 A 59 ANOS,...,1608,22482,ALDEMIRRODRIGUESDEBRITOMASC1608,ALDEMIRRODRIGUESDEBRITO,2021.0,7.0,2021.0,5.0,1,NaN
2,29560445,NaN,NaN,ZULEIDE BORGES MOURA,FEM,NaN,NaN,84,4084.0,80+ ANOS,...,.,.,ZULEIDEBORGESMOURAFEM.,ZULEIDEBORGESMOURA,NaN,NaN,2020.0,5.0,1,NaN
3,29586834,NaN,NaN,IVONETE ROCHA PRACIANO,FEM,08/05/1929,EROTILDES DIAS ROCHA,90,4090.0,80+ ANOS,...,-11195,22033,IVONETEROCHAPRACIANOFEM-11195,IVONETEROCHAPRACIANO,2020.0,4.0,NaN,NaN,1,NaN
4,29606162,NaN,NaN,TARCILIO RODRIGUES BATISTA,MASC,27/10/1970,MARIA DO CARMO RODRIGUES BATISTA,49,4049.0,45 A 49 ANOS,...,3952,22105,TARCILIORODRIGUESBATISTAMASC3952,TARCILIORODRIGUESBATISTA,2020.0,7.0,2020.0,6.0,1,INTEREPIDEMICO

## Death geral

In [14]:
fname_cart = os.path.join("..", "..", "..", "data", "obitos_cartorios", "obitos_cartorios_joined.csv")
df_cart = pd.read_csv(fname_cart, delimiter=",", nrows=None, dtype={"cpf": str}, index_col=0)

C:\Users\higor.monteiro\Miniconda3\envs\geopandas_testenv\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (13,14) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [15]:
print(df_cart.shape[0])
df_cart[:5]

39612

,nome,livro,folha,termo,data nascimento,data falecimento,genitor 1,genitor 2,do,cartorio,registro,documento falecido,naturalidade,sigla estado naturalidade,cpf,rg,do_8
index original,,,,,,,,,,,,,,,,,
0,MELQUISEDEQUE ALVES CAVALCANTE DA SILVA,13.0,249.0,6301.0,20/05/1999,01/01/2020,MÃ¡rio Jorge da Silva PaixÃ£o,Maria Rejane Alves Soares,296264407.0,botelho,NaN,NaN,NaN,NaN,03941885359,NaN,29626440.0
1,JOSÃ HUGO VIANA MESQUITA,13.0,245.0,6297.0,09/05/1951,02/01/2020,Francisco Osmar de Mesquita,Maria Odete de Mesquita,296152110.0,botelho,NaN,NaN,NaN,NaN,06182410353,NaN,29615211.0
2,FRANCE MARIA AMORIM PATRICIO,13.0,247.0,6299.0,11/04/1977,02/01/2020,Raimundo Bianor Patricio,Francineide Amorim Patricio,296148083.0,botelho,NaN,NaN,NaN,NaN,77640918391,NaN,29614808.0
3,MARIA JOSÃ CARNEIRO GIRÃO,13.0,244.0,6296.0,06/07/1931,02/01/2020,Benigno Carneiro de Sousa,Raimunda Carneiro GirÃ£o,277236126.0,botelho,NaN,NaN,NaN,NaN,01571095349,NaN,27723612.0
4,DERMIVAL CAMPOS NOGUEIRA,13.0,242.0,6294.0,16/11/1952,03/01/2020,JoÃ£o Campos Nogueira,Maria de Goes Nogueira,296140538.0,botelho,NaN,NaN,NaN,NaN,07298200330,NaN,29614053.0

In [7]:
eli = pd.read_csv("../output/eligibility_population.csv")
eli["uuid"] = eli["cpf"].apply(lambda x: uuid.uuid4())
eli = eli.drop(["nome", "cpf", "data_nascimento", "nome_mae"], axis=1)

C:\Users\higor.monteiro\Miniconda3\envs\geopandas_testenv\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (22,23,25) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [8]:
eli[:5]

,bairro,sexo,created_at,data D1(VACINADOS),data D2(VACINADOS),vacina(VACINADOS),fornecedor(VACINADOS),idade anos(VACINADOS),faixa etaria(VACINADOS),bairro(VACINADOS),...,OBITO INCONSISTENCIA COVID,OBITO INCONSISTENCIA CARTORIOS,VACINA STATUS - COORTE,IMUNIZACAO MAXIMA ATE FIM DA COORTE,ELIGIBILIDADE TESTE,ELIGIBILIDADE COORTE GERAL,ELIGIBILIDADE EXPOSTO PARCIAL,ELIGIBILIDADE EXPOSTO TOTAL,idade,uuid
0,PASSARE,F,2021-05-26 00:00:00,2021-05-29 00:00:00,2021-08-27 00:00:00,ASTRAZENECA,FIOCRUZ,46.0,45 A 49 ANOS,PASSARE,...,N,N,D1 DURANTE COORTE,PARCIALMENTE IMUNIZADO,APTO,APTO,APTO,NAO APTO,46,1821beba-d687-4043-9511-c5b119a59b79
1,JANGURUSSU,M,2021-04-04 00:00:00,2021-06-04 00:00:00,2021-08-09 00:00:00,ASTRAZENECA,FIOCRUZ,31.0,30 A 34 ANOS,JANGURUSSU,...,N,N,D1 DURANTE COORTE,TOTALMENTE IMUNIZADO,APTO,APTO,NAO APTO,APTO,31,cea99bbf-ba3b-45ef-8bfb-8bf88b0ba179
2,BARRA DO CEARA,F,2021-06-04 00:00:00,2021-06-19 00:00:00,NaN,ASTRAZENECA,FIOCRUZ,44.0,40 A 44 ANOS,BARRA DO CEARA,...,N,N,D1 DURANTE COORTE,PARCIALMENTE IMUNIZADO,APTO,APTO,APTO,NAO APTO,44,6220af70-dad2-48dd-a5c0-eb705ec047ba
3,JANGURUSSU,F,2021-08-04 00:00:00,2021-08-09 00:00:00,NaN,CORONAVAC,BUTANTAN,45.0,45 A 49 ANOS,CENTRO,...,N,N,D1 DURANTE COORTE,PARCIALMENTE IMUNIZADO,APTO,APTO,APTO,NAO APTO,45,f86c4e9a-edc0-441f-b040-50e8be1372d7
4,BONSUCESSO,F,2021-03-26 00:00:00,2021-07-27 00:00:00,NaN,ASTRAZENECA,FIOCRUZ,26.0,25 A 29 ANOS,JOQUEI CLUBE,...,N,N,D1 DURANTE COORTE,PARCIALMENTE IMUNIZADO,APTO,APTO,APTO,NAO APTO,27,4f3c26c1-e113-47f9-ba85-135c781c9ff6

In [ ]:
eli.to_csv(os.path.join("..", "output", "eligibility_population_filter.csv"))