# LIB

In [1]:
import os
from tqdm import tqdm
import pandas as pd
import numpy as np
from collections import defaultdict

# Load data

In [2]:
# Previous eligibility data
exem = pd.read_csv(os.path.join("..", "output", "data", "eligibility_population_21JAN2021_31AUG2021_newbairro1.csv"))

C:\Users\higor.monteiro\Miniconda3\envs\cevepi\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (22,23,25) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
fpath = os.path.join("..", "output", "data", "LINKAGE")
fpathdata = os.path.join("..", "..", "..", "data", "PARQUET_TRANSFORMED")

# --> Linkage data
link_ja_vac = pd.read_parquet(os.path.join(fpath, "VACINEJA_VACINADOS.parquet"))
link_ja_int = pd.read_parquet(os.path.join(fpath, "VACINEJA_INTEGRASUS.parquet"))
link_ja_covid = pd.read_parquet(os.path.join(fpath, "VACINEJA_OBITO_COVID.parquet"))
link_ja_cart = pd.read_parquet(os.path.join(fpath, "VACINEJA_OBITO_CARTORIO.parquet"))

# --> Databases
vacineja_df = pd.read_parquet(os.path.join(fpathdata, "VACINEJA.parquet"))
vacinados_df = pd.read_parquet(os.path.join(fpathdata, "VACINADOS.parquet"))
integra_df = pd.read_parquet(os.path.join(fpathdata, "INTEGRASUS.parquet"))
covid_df = pd.read_parquet(os.path.join(fpathdata, "OBITO_COVID.parquet"))
cart_df = pd.read_parquet(os.path.join(fpathdata, "OBITO_CARTORIO.parquet"))

In [4]:
found_vacinados = link_ja_vac[pd.notna(link_ja_vac["cpf(VACINEJA)"])]
found_tests = link_ja_int[pd.notna(link_ja_int["cpf(VACINEJA)"])]
found_covid = link_ja_covid[pd.notna(link_ja_covid["cpf(VACINEJA)"])]
found_cart = link_ja_cart[pd.notna(link_ja_cart["cpf(VACINEJA)"])]

to_vacinados = defaultdict(lambda: np.nan, zip(found_vacinados["cpf(VACINEJA)"], found_vacinados["cpf(VACINADOS)"]))
to_tests = defaultdict(lambda: np.nan, zip(found_tests["cpf(VACINEJA)"], found_tests["id"]))
to_covid = defaultdict(lambda: np.nan, zip(found_covid["cpf(VACINEJA)"], found_covid["numerodo"]))
to_cart = defaultdict(lambda: np.nan, zip(found_cart["cpf(VACINEJA)"], found_cart["cpf(CARTORIOS)"]))

In [5]:
vacineja_df["cpf LINKAGE VACINADOS"] = vacineja_df["cpf"].apply(lambda x: to_vacinados[x])
vacineja_df["id LINKAGE INTEGRASUS"] = vacineja_df["cpf"].apply(lambda x: to_tests[x])
vacineja_df["numerodo LINKAGE OBITO COVID"] = vacineja_df["cpf"].apply(lambda x: to_covid[x])
vacineja_df["cpf LINKAGE CARTORIOS"] = vacineja_df["cpf"].apply(lambda x: to_cart[x])

In [7]:
vacineja_df[:3]

,nome,cpf,cns,data_nascimento,nome_mae,cep,bairro,sexo,created_at,situacao,cpf LINKAGE VACINADOS,id LINKAGE INTEGRASUS,numerodo LINKAGE OBITO COVID,cpf LINKAGE CARTORIOS
0,FRANCISCA ANA MARIA DE MELO LIMA,67698255387,nan,1974-03-14,TEREZA ARAUJO DE MELO,60450635,NÃO INFOMRADO,F,2022-01-09 19:04:36,RECEBEU AO MENOS UMA DOSE,67698255387,NaN,NaN,NaN
1,WASTERLAY BARROSO PEIXOTO,58931961391,nan,1974-04-02,MARLUCIA BEZERRA BARROSO,60864260,CAJAZEIRAS,M,2022-01-09 19:04:36,RECEBEU AO MENOS UMA DOSE,58931961391,[2322927],NaN,NaN
2,AFONSO DIAS BARRETO JUNIOR,52783847353,nan,1974-08-25,ALBERTINA DIAS BARRETO,60822345,CAMBEBA,M,2022-01-09 19:04:36,RECEBEU AO MENOS UMA DOSE,NaN,NaN,NaN,NaN

In [40]:
integra_df = integra_df.set_index("id")

In [89]:
def select_indexes(integra_df, indexes):
    '''
    
    '''
    selected = integra_df.loc[indexes]
    #print(selected["INFO COORTE SINTOMAS"].values, selected["INFO COORTE SOLICITACAO"].values, selected["INFO COORTE COLETA"].values)
    if np.isin(["SIM"], selected["INFO COORTE SINTOMAS"].values)[0]:
        return "SIM"
    if np.isin(["SIM"], selected["INFO COORTE SOLICITACAO"].values)[0]:
        return "SIM"
    if np.isin(["SIM"], selected["INFO COORTE COLETA"].values)[0]:
        return "SIM"
    return "NAO"

In [92]:
%timeit
vacineja_df["TESTE POSITIVO ANTES COORTE"] = vacineja_df["id LINKAGE INTEGRASUS"].apply(lambda x: select_indexes(integra_df, x) if type(x)!=float else "NAO")

In [91]:
vacineja_df

,nome,cpf,cns,data_nascimento,nome_mae,cep,bairro,sexo,created_at,situacao,cpf LINKAGE VACINADOS,numerodo LINKAGE OBITO COVID,cpf LINKAGE CARTORIOS,id LINKAGE INTEGRASUS,TESTE POSITIVO ANTES COORTE
0,FRANCISCA ANA MARIA DE MELO LIMA,67698255387,nan,1974-03-14,TEREZA ARAUJO DE MELO,60450635,NÃO INFOMRADO,F,2022-01-09 19:04:36,RECEBEU AO MENOS UMA DOSE,67698255387,NaN,NaN,NaN,NaN
1,WASTERLAY BARROSO PEIXOTO,58931961391,nan,1974-04-02,MARLUCIA BEZERRA BARROSO,60864260,CAJAZEIRAS,M,2022-01-09 19:04:36,RECEBEU AO MENOS UMA DOSE,58931961391,NaN,NaN,[2322927],NAO
2,AFONSO DIAS BARRETO JUNIOR,52783847353,nan,1974-08-25,ALBERTINA DIAS BARRETO,60822345,CAMBEBA,M,2022-01-09 19:04:36,RECEBEU AO MENOS UMA DOSE,NaN,NaN,NaN,NaN,NaN
3,GEORGEA GLICIA RODRIGUES,69090580387,nan,1974-10-02,RAIMUNDA FERREIRA RODRIGUES,60871684,MESSEJANA,F,2022-01-09 19:04:36,RECEBEU AO MENOS UMA DOSE,69090580387,NaN,NaN,[440160],NAO
4,JANNAYNA COELHO SAMPAIO,56928815353,705009027322754,1975-03-09,MARIA SYDENIA COELHO SAMPAIO,60810786,SALINAS,F,2022-01-09 19:04:36,RECEBEU AO MENOS UMA DOSE,56928815353,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2515584,MARIANNE VELOSO SILVA,01245896342,nan,1988-01-07,FRANCINETE RODRIGUES VELOSO,60015140,CENTRO,F,2022-01-09 19:04:36,NÃO VACINADO,NaN,NaN,NaN,[3609386],NAO
2515585,LETICIA ANDRADE HOLANDA,07900477306,898004624239913.0,2014-10-03,CARLOS EDUARDO SOMBRA HOLANDA,60182453,NÃO INFOMRADO,M,2022-01-09 19:04:36,NÃO VACINADO,NaN,NaN,NaN,[1877217],NAO
2515587,GISLAINE DO NASCIMENTO JACINTO,12915178470,nan,2001-07-01,FRANCINEIDE DO NASCIMENTO JACINTO,60525570,JOAO XXIII,F,2022-01-09 19:04:36,NÃO VACINADO,NaN,NaN,NaN,NaN,NaN
2515588,AFONSO CORREIA DA SILVA,11424290325,706401137062886.0,1950-03-02,MARIA FECILIA DE MORAIS,60356001,ANTONIO BEZERRA,M,2022-01-09 19:04:36,NÃO VACINADO,NaN,NaN,NaN,NaN,NaN
2515589,RAFAELY CRISTINA CAVALCANTE RABELO,08634714390,nan,2002-05-14,JOSEFA MARINETE LIMA CAVALCANTE,60750080,NÃO INFOMRADO,F,2022-01-09 19:04:36,NÃO VACINADO,NaN,NaN,NaN,NaN,NaN

In [84]:
ss = vacineja_df[pd.notna(vacineja_df["id LINKAGE INTEGRASUS"])][:15]["id LINKAGE INTEGRASUS"].loc[47]

In [85]:
integra_df.loc[ss]

,nome_paciente,nome_mae,cpf,cns,data_nascimento,data_coleta_exame,data_inicio_sintomas_nova,data_internacao_sivep,data_entrada_uti_sivep,data_evolucao_caso_sivep,...,nome hashcode,nome mae tratado,nome mae hashcode,PRIMARY_KEY_PERSON,SINTOMAS ANTES COORTE,SOLICITACAO ANTES COORTE,COLETA ANTES COORTE,INFO COORTE SINTOMAS,INFO COORTE SOLICITACAO,INFO COORTE COLETA
id,,,,,,,,,,,,,,,,,,,,,
406524,ROSIDALVA SANTANA DA COSTA,None,64140865334,,1974-11-02,2021-05-20,2021-05-13,NaT,NaT,NaT,...,RSDC23,None,None,64140865334,NAO,NAO,NAO,NAO,NAO,NAO
1244498,ROSIVALDA SANTANA DA COSTA,None,64140865334,,1974-11-02,2021-05-19,2021-05-19,NaT,NaT,NaT,...,RSDC23,None,None,64140865334,NAO,NAO,NAO,NAO,NAO,NAO

In [83]:
pd.isna([1])

array([False])

In [104]:
drop_list =  ["id", "estabelecimento_razao_social", "sistema_origem", "document_id", "paciente_endereco_bairro", "paciente_indigena", "estabelecimento_uf", 
              "paciente_nacionalidade", "estabelecimento_valor", "vacina_grupo_atendimento_codigo", "data_importacao_datalake", "vacina_grupo_atendimento_nome",
              "paciente_id", "vacina_categoria_codigo", "paciente_endereco_pais", "paciente_endereco_cep", "vacina_lote" "paciente_cns", "paciente_endereco_municipio",
              "estabelecimento_municipio_codigo", "vacina_profissional_aplicador_no", "estabelecimento_municipio_nome", "data_importacao_rnds" "timestamp",
              "vacina_profissional_aplicador" "paciente_endereco_uf", "paciente_endereco_co_pais", "vacina_profissional_aplicador_cp", "vacina_fabricante_referencia",
              "data_atualizacao", "data_criacao"]

In [105]:
fpathvac = os.path.join("..", "..", "..", "data", "vacinado_obito")
df = pd.read_csv(os.path.join(fpathvac, "sipni.csv"), delimiter=";", nrows=10)
cols = list(df.columns)
cols = [x.lower() for x in cols ]
cols = [x.lower() for x in cols if x not in drop_list]
cols = [x.upper() for x in cols if x!="version" ] + ["Version"]

In [106]:
df = pd.read_csv(os.path.join(fpathvac, "sipni.csv"), delimiter=";", usecols=cols, nrows=None)

C:\Users\higor.monteiro\Miniconda3\envs\cevepi\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (16,28,34) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [109]:
df.shape

(14055216, 23)

In [108]:
fp = os.path.join("..", "..", "..", "data", "VACINADOS_PAT_CEARA_REDUZIDO.csv")
df.to_csv(fp, index=False)

In [110]:
#%%timeit
#rows = 0
#chunksize=50000
#data_iter = pd.read_csv(os.path.join(fpathvac, "sipni.csv"), delimiter=";", chunksize=chunksize, engine="python")
#for df in tqdm(data_iter):
#    rows += df.shape[0]

In [111]:
#23*4*28

In [112]:
#14000000/500000

In [113]:
#45/2

In [115]:
df = 0

In [14]:
import json
idlst = [6,12,39]
sub = integra_df.loc[idlst]
dict(zip(sub["data_coleta_exame"], sub["resultado_final_exame"]))

{Timestamp('2021-04-05 00:00:00'): 'POSITIVO',
 Timestamp('2021-02-08 00:00:00'): 'POSITIVO',
 Timestamp('2021-06-14 00:00:00'): 'POSITIVO'}

In [12]:
integra_df["data_coleta_exame"].isnull().sum()

44811

In [ ]:
i