# Verifications Post-analysis

## Lib

In [50]:
import os
import pandas as pd
import numpy as np
import datetime as dt

import matplotlib.pyplot as plt
%matplotlib inline

## Set config and paths

In [78]:
inputs = {
    "folder": lambda hdi_index: f"PRI_NA_COORTEX_HDI_{hdi_index}_21JAN2021_31AUG2021",
    "only_events": lambda seed: f"EVENTOS_PAREADOS_{seed}.parquet",
    "only_pairs": lambda seed: f"PAREADOS_CPF_{seed}.parquet",
    "pairs_events_int": lambda event, seed: f"PAREADOS_COM_INTERVALOS_{event}_{seed}.parquet",
    "survival_int": lambda event, seed: f"SURVIVAL_CORONAVAC_D1D2_{event}_{seed}.parquet"
}

config = {
    "seed": 1,
    "hdi_index": 2,
    "event": "OBITO",
}

schema_path = os.path.join( "..", "output", "data", "SCHEMA_21JAN2021_31AUG2021.parquet")
base_path = os.path.join( "..", "output", "PAREAMENTO", "CORONAVAC", inputs["folder"](config["hdi_index"]) )
pairs_path = os.path.join( base_path, inputs["only_pairs"](config['seed']) )
events_path = os.path.join( base_path, inputs["only_events"](config['seed']) )
pairs_events_path = os.path.join( base_path, inputs["pairs_events_int"](config['event'], config['seed']) )
survival_path_death = os.path.join( base_path, "SURVIVAL", inputs['survival_int']('OBITO', config['seed']) )
survival_path_hosp = os.path.join( base_path, "SURVIVAL", inputs['survival_int']('HOSPITAL', config['seed']) )
survival_path_icu = os.path.join( base_path, "SURVIVAL", inputs['survival_int']('UTI', config['seed']) )

## Load data

In [59]:
fschema_df = pd.read_parquet(schema_path)

In [81]:
pairs_df = pd.read_parquet(pairs_path)
events_df = pd.read_parquet(events_path)
pairs_events_df = pd.read_parquet(pairs_events_path)
survival_df_death = pd.read_parquet(survival_path_death)
survival_df_hosp = pd.read_parquet(survival_path_hosp)
survival_df_icu = pd.read_parquet(survival_path_icu)

In [82]:
events_df = events_df[events_df["TIPO"]!="NAO PAREADO"]

def new_hospitalization_date(x, cohort):
    '''
    
    '''
    if not np.any(pd.notna(x)):
        return np.nan
    x = np.sort([xx for xx in x if pd.notna(xx)]) 
    condition = (x>=cohort[0]) & (x<=cohort[1])
    if x[condition].shape[0]>0:
        return x[condition][0]
    else:
        return np.nan
    
events_df["DATA HOSPITALIZACAO"] = events_df["DATA HOSPITALIZACAO"].apply(lambda x: new_hospitalization_date(x, (dt.datetime(2021,1,21), dt.datetime(2021,8,31))))
events_df["DATA UTI"] = events_df["DATA UTI"].apply(lambda x: new_hospitalization_date(x, (dt.datetime(2021,1,21), dt.datetime(2021,8,31))))

## Count of events

In [83]:
survival_death = pd.read_parquet(os.path.join( base_path, "SURVIVAL", inputs['survival_int']("OBITO", config['seed']) ))
survival_hosp = pd.read_parquet(os.path.join( base_path, "SURVIVAL", inputs['survival_int']("HOSPITAL", config['seed']) ))
survival_icu = pd.read_parquet(os.path.join( base_path, "SURVIVAL", inputs['survival_int']("UTI", config['seed']) ))

data = {
    "OBITO (day 100)": [0,0,0,0], "HOSPITAL (day 100)": [0,0,0,0], "UTI (day 100)": [0,0,0,0],
    "OBITO (day end)": [0,0,0,0], "HOSPITAL (day end)": [0,0,0,0], "UTI (day end)": [0,0,0,0],
}

survival, survival_names = [survival_death, survival_hosp, survival_icu], ["OBITO", "HOSPITAL", "UTI"]
for index, df in enumerate(survival):
    surv_caso_100 = df[(df["TIPO"]=="CASO") & (df[f"t - D1 {survival_names[index]}"]<=30) & (df[f"t - D1 {survival_names[index]}"]>=0)]
    surv_controle_100 = df[(df["TIPO"]=="CONTROLE") & (df[f"t - D1 {survival_names[index]}"]<=30) & (df[f"t - D1 {survival_names[index]}"]>=0)]
    surv_caso = df[(df["TIPO"]=="CASO")]
    surv_controle = df[(df["TIPO"]=="CONTROLE")]
    
    caso_total_d1 = surv_caso[f"t - D1 {survival_names[index]}"].notnull().sum()
    controle_total_d1 = surv_controle[f"t - D1 {survival_names[index]}"].notnull().sum()
    caso_total_d2 = surv_caso[f"t - D2 {survival_names[index]}"].notnull().sum()
    controle_total_d2 = surv_controle[f"t - D2 {survival_names[index]}"].notnull().sum()
    
    caso_event_d1_100 = surv_caso_100[f"E - D1 {survival_names[index]}"].value_counts().loc[True]
    caso_event_d2_100 = surv_caso_100[f"E - D2 {survival_names[index]}"].value_counts().loc[True]
    controle_event_d1_100 = surv_controle_100[f"E - D1 {survival_names[index]}"].value_counts().loc[True]
    controle_event_d2_100 = surv_controle_100[f"E - D2 {survival_names[index]}"].value_counts().loc[True]
    
    caso_event_d1 = surv_caso[f"E - D1 {survival_names[index]}"].value_counts().loc[True]
    caso_event_d2 = surv_caso[f"E - D2 {survival_names[index]}"].value_counts().loc[True]
    controle_event_d1 = surv_controle[f"E - D1 {survival_names[index]}"].value_counts().loc[True]
    controle_event_d2 = surv_controle[f"E - D2 {survival_names[index]}"].value_counts().loc[True]
    
    data[f"{survival_names[index]} (day 100)"][0] = f"{caso_event_d1_100}/{caso_total_d1}"
    data[f"{survival_names[index]} (day 100)"][1] = f"{controle_event_d1_100}/{controle_total_d1}"
    data[f"{survival_names[index]} (day 100)"][2] = f"{caso_event_d2_100}/{caso_total_d2}"
    data[f"{survival_names[index]} (day 100)"][3] = f"{controle_event_d2_100}/{controle_total_d2}"
    
    data[f"{survival_names[index]} (day end)"][0] = f"{caso_event_d1}/{caso_total_d1}"
    data[f"{survival_names[index]} (day end)"][1] = f"{controle_event_d1}/{controle_total_d1}"
    data[f"{survival_names[index]} (day end)"][2] = f"{caso_event_d2}/{caso_total_d2}"
    data[f"{survival_names[index]} (day end)"][3] = f"{controle_event_d2}/{controle_total_d2}"

data = pd.DataFrame(data)
data.index = ["CASO D1", "CONTROLE D1", "CASO D2", "CONTROLE D2"]

In [84]:
data

,OBITO (day 100),HOSPITAL (day 100),UTI (day 100),OBITO (day end),HOSPITAL (day end),UTI (day end)
CASO D1,40/144393,256/144393,56/144393,57/144393,277/144393,62/144393
CONTROLE D1,37/144393,256/144393,58/144393,42/144393,277/144393,65/144393
CASO D2,18/62658,255/62380,42/62626,22/62658,286/62380,50/62626
CONTROLE D2,117/62658,442/62380,110/62626,132/62658,500/62380,126/62626

## Events by condition

In [ ]:
events = events_df[(events_df["DATA OBITO COVID"]>=dt.datetime(2021,1,21)) | pd.isna(events_df["DATA OBITO COVID"])]

events_caso = events[events["TIPO"]=="CASO"].copy()
events_controle = events[events["TIPO"]=="CONTROLE"].copy()

# --> Geral
caso_obito_geral = events_caso["DATA OBITO COVID"].notnull().sum()
caso_hosp_geral = events_caso["DATA HOSPITALIZACAO"].notnull().sum()
caso_uti_geral = events_caso["DATA UTI"].notnull().sum()
controle_obito_geral = events_controle["DATA OBITO COVID"].notnull().sum()
controle_hosp_geral = events_controle["DATA HOSPITALIZACAO"].notnull().sum()
controle_uti_geral = events_controle["DATA UTI"].notnull().sum()

# --> Antes D1
func_1 = lambda x: True if pd.notna(x["DATA D1"]) and pd.notna(x["DATA OBITO COVID"]) and x["DATA OBITO COVID"]<x["DATA D1"] else ( True if pd.isna(x["DATA D1"]) and pd.notna(x["DATA OBITO COVID"]) else False)
events_caso["OBITO ANTES D1"] = events_caso[["DATA D1", "DATA OBITO COVID"]].apply(func_1, axis=1)
events_controle["OBITO ANTES D1"] = events_controle[["DATA D1", "DATA OBITO COVID"]].apply(func_1, axis=1)
# --
func_1 = lambda x: True if pd.notna(x["DATA D1"]) and pd.notna(x["DATA HOSPITALIZACAO"]) and x["DATA HOSPITALIZACAO"]<x["DATA D1"] else ( True if pd.isna(x["DATA D1"]) and pd.notna(x["DATA HOSPITALIZACAO"]) else False)
events_caso["HOSP ANTES D1"] = events_caso[["DATA D1", "DATA HOSPITALIZACAO"]].apply(func_1, axis=1)
events_controle["HOSP ANTES D1"] = events_controle[["DATA D1", "DATA HOSPITALIZACAO"]].apply(func_1, axis=1)
# --
func_1 = lambda x: True if pd.notna(x["DATA D1"]) and pd.notna(x["DATA UTI"]) and x["DATA UTI"]<x["DATA D1"] else ( True if pd.isna(x["DATA D1"]) and pd.notna(x["DATA UTI"]) else False)
events_caso["UTI ANTES D1"] = events_caso[["DATA D1", "DATA UTI"]].apply(func_1, axis=1)
events_controle["UTI ANTES D1"] = events_controle[["DATA D1", "DATA UTI"]].apply(func_1, axis=1)
# ----> counting
caso_obito_antesd1 = events_caso[events_caso["OBITO ANTES D1"]==True].shape[0]
controle_obito_antesd1 = events_controle[events_controle["OBITO ANTES D1"]==True].shape[0]
caso_hosp_antesd1 = events_caso[events_caso["HOSP ANTES D1"]==True].shape[0]
controle_hosp_antesd1 = events_controle[events_controle["HOSP ANTES D1"]==True].shape[0]
caso_uti_antesd1 = events_caso[events_caso["UTI ANTES D1"]==True].shape[0]
controle_uti_antesd1 = events_controle[events_controle["UTI ANTES D1"]==True].shape[0]

# --> Apos D1
func_2 = lambda x: True if pd.notna(x["DATA D1"]) and pd.notna(x["DATA OBITO COVID"]) and x["DATA OBITO COVID"]>=x["DATA D1"] else False
events_caso["OBITO APOS D1"] = events_caso[["DATA D1", "DATA OBITO COVID"]].apply(func_2, axis=1)
events_controle["OBITO APOS D1"] = events_controle[["DATA D1", "DATA OBITO COVID"]].apply(func_2, axis=1)
# --
func_2 = lambda x: True if pd.notna(x["DATA D1"]) and pd.notna(x["DATA HOSPITALIZACAO"]) and x["DATA HOSPITALIZACAO"]>=x["DATA D1"] else False
events_caso["HOSP APOS D1"] = events_caso[["DATA D1", "DATA HOSPITALIZACAO"]].apply(func_2, axis=1)
events_controle["HOSP APOS D1"] = events_controle[["DATA D1", "DATA HOSPITALIZACAO"]].apply(func_2, axis=1)
# --
func_2 = lambda x: True if pd.notna(x["DATA D1"]) and pd.notna(x["DATA UTI"]) and x["DATA UTI"]>=x["DATA D1"] else False
events_caso["UTI APOS D1"] = events_caso[["DATA D1", "DATA UTI"]].apply(func_2, axis=1)
events_controle["UTI APOS D1"] = events_controle[["DATA D1", "DATA UTI"]].apply(func_2, axis=1)
# ----> counting
caso_obito_aposd1 = events_caso[events_caso["OBITO APOS D1"]==True].shape[0]
controle_obito_aposd1 = events_controle[events_controle["OBITO APOS D1"]==True].shape[0]
caso_hosp_aposd1 = events_caso[events_caso["HOSP APOS D1"]==True].shape[0]
controle_hosp_aposd1 = events_controle[events_controle["HOSP APOS D1"]==True].shape[0]
caso_uti_aposd1 = events_caso[events_caso["UTI APOS D1"]==True].shape[0]
controle_uti_aposd1 = events_controle[events_controle["UTI APOS D1"]==True].shape[0]

# --> Antes D2
func_3 = lambda x: True if pd.notna(x["DATA D2"]) and pd.notna(x["DATA OBITO COVID"]) and x["DATA OBITO COVID"]<x["DATA D2"] else ( True if pd.isna(x["DATA D2"]) and pd.notna(x["DATA OBITO COVID"]) else False)
events_caso["OBITO ANTES D2"] = events_caso[["DATA D2", "DATA OBITO COVID"]].apply(func_3, axis=1)
events_controle["OBITO ANTES D2"] = events_controle[["DATA D2", "DATA OBITO COVID"]].apply(func_3, axis=1)
# --
func_3 = lambda x: True if pd.notna(x["DATA D2"]) and pd.notna(x["DATA HOSPITALIZACAO"]) and x["DATA HOSPITALIZACAO"]<x["DATA D2"] else ( True if pd.isna(x["DATA D2"]) and pd.notna(x["DATA HOSPITALIZACAO"]) else False)
events_caso["HOSP ANTES D2"] = events_caso[["DATA D2", "DATA HOSPITALIZACAO"]].apply(func_3, axis=1)
events_controle["HOSP ANTES D2"] = events_controle[["DATA D2", "DATA HOSPITALIZACAO"]].apply(func_3, axis=1)
# --
func_3 = lambda x: True if pd.notna(x["DATA D2"]) and pd.notna(x["DATA UTI"]) and x["DATA UTI"]<x["DATA D2"] else ( True if pd.isna(x["DATA D2"]) and pd.notna(x["DATA UTI"]) else False)
events_caso["UTI ANTES D2"] = events_caso[["DATA D2", "DATA UTI"]].apply(func_3, axis=1)
events_controle["UTI ANTES D2"] = events_controle[["DATA D2", "DATA UTI"]].apply(func_3, axis=1)
# ----> counting
caso_obito_antesd2 = events_caso[events_caso["OBITO ANTES D2"]==True].shape[0]
controle_obito_antesd2 = events_controle[events_controle["OBITO ANTES D2"]==True].shape[0]
caso_hosp_antesd2 = events_caso[events_caso["HOSP ANTES D2"]==True].shape[0]
controle_hosp_antesd2 = events_controle[events_controle["HOSP ANTES D2"]==True].shape[0]
caso_uti_antesd2 = events_caso[events_caso["UTI ANTES D2"]==True].shape[0]
controle_uti_antesd2 = events_controle[events_controle["UTI ANTES D2"]==True].shape[0]

# --> Apos D2
func_4 = lambda x: True if pd.notna(x["DATA D2"]) and pd.notna(x["DATA OBITO COVID"]) and x["DATA OBITO COVID"]>=x["DATA D2"] else False
events_caso["OBITO APOS D2"] = events_caso[["DATA D2", "DATA OBITO COVID"]].apply(func_4, axis=1)
events_controle["OBITO APOS D2"] = events_controle[["DATA D2", "DATA OBITO COVID"]].apply(func_4, axis=1)
# --
func_4 = lambda x: True if pd.notna(x["DATA D2"]) and pd.notna(x["DATA HOSPITALIZACAO"]) and x["DATA HOSPITALIZACAO"]>=x["DATA D2"] else False
events_caso["HOSP APOS D2"] = events_caso[["DATA D2", "DATA HOSPITALIZACAO"]].apply(func_4, axis=1)
events_controle["HOSP APOS D2"] = events_controle[["DATA D2", "DATA HOSPITALIZACAO"]].apply(func_4, axis=1)
# --
func_4 = lambda x: True if pd.notna(x["DATA D2"]) and pd.notna(x["DATA UTI"]) and x["DATA UTI"]>=x["DATA D2"] else False
events_caso["UTI APOS D2"] = events_caso[["DATA D2", "DATA UTI"]].apply(func_4, axis=1)
events_controle["UTI APOS D2"] = events_controle[["DATA D2", "DATA UTI"]].apply(func_4, axis=1)
# ----> counting
caso_obito_aposd2 = events_caso[events_caso["OBITO APOS D2"]==True].shape[0]
controle_obito_aposd2 = events_controle[events_controle["OBITO APOS D2"]==True].shape[0]
caso_hosp_aposd2 = events_caso[events_caso["HOSP APOS D2"]==True].shape[0]
controle_hosp_aposd2 = events_controle[events_controle["HOSP APOS D2"]==True].shape[0]
caso_uti_aposd2 = events_caso[events_caso["UTI APOS D2"]==True].shape[0]
controle_uti_aposd2 = events_controle[events_controle["UTI APOS D2"]==True].shape[0]

# --> Censured
caso_survival_death = survival_df_death[survival_df_death['TIPO']=="CASO"]
controle_survival_death = survival_df_death[survival_df_death['TIPO']=="CONTROLE"]
caso_survival_hosp = survival_df_hosp[survival_df_hosp['TIPO']=="CASO"]
controle_survival_hosp = survival_df_hosp[survival_df_hosp['TIPO']=="CONTROLE"]
caso_survival_icu = survival_df_icu[survival_df_icu['TIPO']=="CASO"]
controle_survival_icu = survival_df_icu[survival_df_icu['TIPO']=="CONTROLE"]

censured_caso_death_d1 = caso_survival_death[caso_survival_death["E - D1 OBITO"]==True].shape[0]
censured_caso_death_d2 = caso_survival_death[caso_survival_death["E - D2 OBITO"]==True].shape[0]
censured_controle_death_d1 = controle_survival_death[controle_survival_death["E - D1 OBITO"]==True].shape[0]
censured_controle_death_d2 = controle_survival_death[controle_survival_death["E - D2 OBITO"]==True].shape[0]
# --
censured_caso_hosp_d1 = caso_survival_hosp[caso_survival_hosp["E - D1 HOSPITAL"]==True].shape[0]
censured_caso_hosp_d2 = caso_survival_hosp[caso_survival_hosp["E - D2 HOSPITAL"]==True].shape[0]
censured_controle_hosp_d1 = controle_survival_hosp[controle_survival_hosp["E - D1 HOSPITAL"]==True].shape[0]
censured_controle_hosp_d2 = controle_survival_hosp[controle_survival_hosp["E - D2 HOSPITAL"]==True].shape[0]
# --
censured_caso_icu_d1 = caso_survival_icu[caso_survival_icu["E - D1 UTI"]==True].shape[0]
censured_caso_icu_d2 = caso_survival_icu[caso_survival_icu["E - D2 UTI"]==True].shape[0]
censured_controle_icu_d1 = controle_survival_icu[controle_survival_icu["E - D1 UTI"]==True].shape[0]
censured_controle_icu_d2 = controle_survival_icu[controle_survival_icu["E - D2 UTI"]==True].shape[0]


data = pd.DataFrame({"CASO GERAL": [caso_obito_geral, caso_hosp_geral, caso_uti_geral],
                     "CONTROLE GERAL": [controle_obito_geral, controle_hosp_geral, controle_uti_geral],
                     "CASO ANTES D1": [caso_obito_antesd1, caso_hosp_antesd1, caso_uti_antesd1],
                     "CASO APOS D1": [caso_obito_aposd1, caso_hosp_aposd1, caso_uti_aposd1],
                     "CASO ANTES D2": [caso_obito_antesd2, caso_hosp_antesd2, caso_uti_antesd2],
                     "CASO APOS D2": [caso_obito_aposd2, caso_hosp_aposd2, caso_uti_aposd2],
                     "CONTROLE ANTES D1": [controle_obito_antesd1, controle_hosp_antesd1, controle_uti_antesd1],
                     "CONTROLE APOS D1": [controle_obito_aposd1, controle_hosp_aposd1, controle_uti_aposd1],
                     "CONTROLE ANTES D2": [controle_obito_antesd2, controle_hosp_antesd2, controle_uti_antesd2],
                     "CONTROLE APOS D2": [controle_obito_aposd2, controle_hosp_aposd2, controle_uti_aposd2],
                     "CASO NAO CENSURADO D1": [censured_caso_death_d1,censured_caso_hosp_d1,censured_caso_icu_d1],
                     "CONTROLE NAO CENSURADO D1": [censured_controle_death_d1,censured_controle_hosp_d1,censured_controle_icu_d1],
                     "CASO NAO CENSURADO D2": [censured_caso_death_d2,censured_caso_hosp_d2,censured_caso_icu_d2],
                     "CONTROLE NAO CENSURADO D2": [censured_controle_death_d2,censured_controle_hosp_d2,censured_controle_icu_d2]})
data.index = ["OBITO", "HOSPITAL", "UTI"]

In [ ]:
data

In [80]:
survival_df_death

,CPF,TIPO,t - D1 OBITO,E - D1 OBITO,t - D2 OBITO,E - D2 OBITO
0,13933680344,CASO,24.0,False,86.0,False
1,30238714349,CONTROLE,24.0,False,86.0,False
2,10965394387,CASO,24.0,False,198.0,False
3,12364231353,CONTROLE,24.0,False,198.0,False
4,25949160304,CASO,26.0,False,47.0,False
...,...,...,...,...,...,...
290139,36601497304,CONTROLE,0.0,False,NaN,False
290140,31823572391,CASO,0.0,False,NaN,False
290141,47264713334,CONTROLE,0.0,False,NaN,False
290142,63368641387,CASO,0.0,False,NaN,False
290143,25479830287,CONTROLE,0.0,False,NaN,False

In [10]:
surv = survival_death
surv_caso = surv[surv["TIPO"]=="CASO"]
surv_controle = surv[surv["TIPO"]=="CONTROLE"]

In [55]:
surv_caso["E - D1 HOSPITAL"].value_counts()

False    144795
True        277
Name: E - D1 HOSPITAL, dtype: int64

In [56]:
surv_controle["E - D1 HOSPITAL"].value_counts()

False    144795
True        277
Name: E - D1 HOSPITAL, dtype: int64

In [66]:
from lifelines import KaplanMeierFitter

In [71]:
df_c = surv_caso[pd.notna(surv_caso["t - D1 OBITO"])]
kmf_caso = KaplanMeierFitter(label="caso")
kmf_caso.fit(df_c["t - D1 OBITO"], df_c["E - D1 OBITO"])

In [50]:
df_c = surv_controle[pd.notna(surv_controle["t - D1 OBITO"])]
kmf_controle = KaplanMeierFitter(label="controle")
kmf_controle.fit(df_c["t - D1 OBITO"], df_c["E - D1 OBITO"])

In [46]:
surv_controle[pd.isna(surv_controle["t - D1 OBITO"])]
surv_caso[pd.isna(surv_caso["t - D1 OBITO"])]

,CPF,TIPO,t - D1 OBITO,E - D1 OBITO,t - D2 OBITO,E - D2 OBITO
6624,14284405349,CASO,NaN,False,81.0,False
6890,13593340330,CASO,NaN,False,66.0,False
6976,19059337387,CASO,NaN,False,84.0,False
7056,27816206372,CASO,NaN,False,65.0,False
7070,07345879372,CASO,NaN,False,42.0,False
...,...,...,...,...,...,...
289108,30147484391,CASO,NaN,False,106.0,False
289546,13604651387,CASO,NaN,False,NaN,False
289744,72114665372,CASO,NaN,False,60.0,False
289974,15441482320,CASO,NaN,False,167.0,False
289990,08656742809,CASO,NaN,False,NaN,False

In [39]:
events_df[events_df["CPF"]=="30147484391"]

,CPF,DATA D1,DATA D2,DATA OBITO COVID,DATA OBITO GERAL,DATA HOSPITALIZACAO,DATA UTI,TIPO,PAR,PAREADO
236429,30147484391,2021-05-18,2021-05-17,NaT,NaT,None,None,CONTROLE,41932480382,True
289110,30147484391,2021-05-18,2021-05-17,NaT,NaT,None,None,CASO,18778070368,True

In [49]:
kmf_caso.event_table["observed"].sum()

57

In [51]:
kmf_controle.event_table["observed"].sum()

42

In [72]:
kmf_caso.event_table

          removed  observed  censored  entrance  at_risk
event_at
0.0          5897         0      5897    144393   144393
1.0         23347         0     23347         0   138496
2.0          6810         0      6810         0   115149
3.0         10769         0     10769         0   108339
4.0          5775         0      5775         0    97570
...           ...       ...       ...       ...      ...
201.0           2         0         2         0        6
206.0           1         0         1         0        4
209.0           1         0         1         0        3
216.0           1         0         1         0        2
217.0           1         0         1         0        1

[164 rows x 5 columns]

In [75]:
kmf_caso.survival_table_from_events

AttributeError: 'KaplanMeierFitter' object has no attribute 'survival_table_from_events'

In [19]:
41+49+20+130

240